dataset_path: '../data/OMNI_COCO'
num_classes: 11 # 1 class (your object) + background
neighbor_num: 5
gpu_ids: '2'
batch_size: 6
learning_rate: 0.0001
weight_decay: 0.05


evaluate: True
exp_name: 'test'
num_workers: 8
arc: 'resnet34'
num_proposals: 50
